---
apiVersion: v1
kind: Service
metadata:
  name: launcher-svc
  labels:
    app: stream-launcher
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: server
  type: NodePort
  selector:
    app: stream-launcher
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: stream-launcher
spec:
  serviceName: launcher-svc
  replicas: 1
  template:
    metadata:
      labels:
          app: stream-launcher
    spec:
      containers:
      - name: stream-launcher
        imagePullPolicy: Always
        image: docker.io/ctslater/stream-launcher:v0.1.3
        resources:
          requests:
            memory: "500m"
            cpu: 500m
        ports:
        - containerPort: 8000
          name: server
      serviceAccount: launcher-account
