
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: alert-stream
spec:
  selector:
    matchLabels:
      app: alert-stream
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: alert-stream
    spec:
      containers:
      - name: alert-stream
        image: docker.io/ctslater/alert_stream:v0.1
        imagePullPolicy: Always
        command: 
          - "python"
        args: ["bin/sendAlertStream.py", "ztf-stream", "20171207", "60"]
        env:
          - name: KAFKA_SERVER
            value: "kafka-0.kafka-svc.default.svc.cluster.local:9093"
          - name: ALERT_DATA
            value: "/home/alert_stream/data"
        resources:
          requests:
            memory: "500m"
            cpu: 500m
        volumeMounts:
        - name: alert-data-dir
          mountPath: /home/alert_stream/data
      volumes:
      - name: alert-data-dir
        hostPath:
          path: /home/centos/alert-data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
